### ISSUE TITLE
No suitable icon

### ISSUE THREAD

**Issue by urakagi** [PDIS/sandmd#3]
Contact HackMD design team?

**Comment by urakagi** [comment]
![sandstorm-sandmd-icon-issue](https://user-images.githubusercontent.com/2368060/45412269-cfb05180-b6a8-11e8-8e74-964f138b38e3.png)

**Comment by jackycute** [comment]
![fb_pic](https://user-images.githubusercontent.com/2639151/45450901-ca1f2f80-b6d9-11e8-84ea-362423c41c6f.png)

請用這個圖檔

**Comment by urakagi** [comment]
![image](https://user-images.githubusercontent.com/2368060/45462937-99241680-b73c-11e8-9e7e-6a1bc002503d.png)

感覺好像留白太大了？
